// GET PRODUCTS
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_TOPPINGS_REQUEST = "GET_TOPPINGS_REQUEST";
export const GET_TOPPINGS_SUCCESS = "GET_TOPPINGS_SUCCESS";
export const GET_TOPPINGS_FAILURE = "GET_TOPPINGS_FAILURE";

export const GET_TOPPING_GROUPS_REQUEST = "GET_TOPPING_GROUPS_REQUEST";
export const GET_TOPPINGS_GROUPS_SUCCESS = "GET_TOPPINGS_GROUPS_SUCCESS";
export const GET_TOPPINGS_GROUPS_FAILURE = "GET_TOPPINGS_GROUPS_FAILURE";

export const CREATE_TOPPING_GROUPS_REQUEST = "CREATE_TOPPING_GROUPS_REQUEST";
export const CREATE_TOPPINGS_GROUPS_SUCCESS = "CREATE_TOPPINGS_GROUPS_SUCCESS";
export const CREATE_TOPPINGS_GROUPS_FAILURE = "CREATE_TOPPINGS_GROUPS_FAILURE";

export const UPDATE_TOPPING_GROUPS_REQUEST = "UPDATE_TOPPING_GROUPS_REQUEST";
export const UPDATE_TOPPINGS_GROUPS_SUCCESS = "UPDATE_TOPPINGS_GROUPS_SUCCESS";
export const UPDATE_TOPPINGS_GROUPS_FAILURE = "UPDATE_TOPPINGS_GROUPS_FAILURE";

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = " GET_CATEGORIES_FAILURE";

export const CREATE_CATEGORIES_REQUEST = "CREATE_CATEGORIES_REQUEST";
export const CREATE_CATEGORIES_SUCCESS = "CREATE_CATEGORIES_SUCCESS";
export const CREATE_CATEGORIES_FAILURE = " CREATE_CATEGORIES_FAILURE";

export const UPDATE_CATEGORIES_REQUEST = "UPDATE_CATEGORIES_REQUEST";
export const UPDATE_CATEGORIES_SUCCESS = "UPDATE_CATEGORIES_SUCCESS";
export const UPDATE_CATEGORIES_FAILURE = "UPDATE_CATEGORIES_FAILURE";

// GET ONE PRODUCT
export const GET_ONE_PRODUCT_REQUEST = "GET_ONE_PRODUCT_REQUEST";
export const GET_ONE_PRODUCT_SUCCESS = "GET_ONE_PRODUCT_SUCCESS";
export const GET_ONE_PRODUCT_FAILURE = "GET_ONE_PRODUCT_FAILURE";

// CREATE PRODUCT
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";

// UPDATE PRODUCT
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";
